version: "3.8"

services:
  database:
    image: postgres
    container_name: db_library
    environment:
      POSTGRES_USER: ${DATABASE_USER} 
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} 
    ports:
      - "5432:5432"
    volumes: 
      - ./config-files/sql:/docker-entrypoint-initdb.d
      - library_data:/var/lib/postgresql/data
    networks:
      - backend
  
  config-server:
    build:
      context: ./config-server
      dockerfile: cloud/docker/Dockerfile
    container_name: config-server
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/rafaelshayashi/library-ddd-by-example-spring-mvc-config-server-files 
      SERVER_PORT: 8080
    networks:
      - backend

  sso:
    image: quay.io/keycloak/keycloak:12.0.4
    container_name: sso
    environment:
      KEYCLOAK_USER: ${SSO_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${SSO_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/jboss/config/library-realm-export.json
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: sso_keycloak
      DB_SCHEMA: public
      DB_PASSWORD: pass_sso_keycloak
    command: ["-Djboss.http.port=9000"]
    ports:
      - "9000:9000"
    volumes:
      - ./config-files/keycloak:/opt/jboss/config
    networks:
      - backend
    
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config-files/nginx/config:/etc/nginx/conf.d
    networks:
      - backend

volumes:
  library_data:

networks:
  backend:
