name: deploy-catalogue

on:
  push:
    branches: [ main ]
    paths: 
      - catalogue/**
      
  workflow_dispatch:

defaults:
  run:
    working-directory: ./catalogue
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
          
      - name: build with gradle
        run: ./gradlew clean build
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: | 
          docker build -t rafaelshayashi/library-catalogue -f cloud/docker/Dockerfile .
          docker push rafaelshayashi/library-catalogue

          
